name: foundry_monorepo

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  melos: ^7.5.1

melos:
  categories:
    e2e:
      - packages/foundry_core/e2e
      - packages/foundry_cli/e2e
    publishable:
      - packages/foundry_core
      - packages/foundry_cli

  repository: https://github.com/mrverdant13/foundry

  command:
    bootstrap:
      environment:
        sdk: ">=3.0.0 <4.0.0"

workspace:
  - packages/foundry_core/
  - packages/foundry_core/e2e/
  - packages/foundry_cli/
  - packages/foundry_cli/e2e/
