name: foundry_core
description: >-
  Core library for Foundry — mold parsing, variable resolution, template
  rendering, and cast orchestration.
version: 0.0.1-dev.1
homepage: https://github.com/mrverdant13/foundry
repository: https://github.com/mrverdant13/foundry/tree/main/packages/foundry_core
issue_tracker: https://github.com/mrverdant13/foundry/issues
topics:
  - mason
  - template
  - codegen
  - yaml
  - liquid

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  checked_yaml: ^2.0.4
  glob: ^2.1.3
  liquify: ^1.5.1
  meta: ^1.15.0
  path: ^1.9.1
  pubspec_parse: ^1.5.0
  recase: ^4.1.0

dev_dependencies:
  pub_score_checker:
    git:
      url: https://github.com/mrverdant13/pub_score_checker.git
      ref: 526653ebf1ea09b3376550edc0ce03a153ca62f2
  test: ^1.31.1
  very_good_analysis: ^10.0.0
  yaml: ^3.1.3
